# Generated by Django 3.2.5 on 2021-07-21 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='제목', max_length=128)),
                ('content', models.CharField(help_text='본문내용', max_length=1000)),
            ],
            options={
                'db_table': 'boards',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='이름', max_length=128)),
                ('password', models.CharField(help_text='패스워드', max_length=128)),
                ('email', models.CharField(help_text='이메일', max_length=45)),
                ('phone', models.CharField(help_text='전화번호', max_length=20)),
                ('is_active', models.SmallIntegerField(help_text='활동 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성일', null=True)),
                ('updated_at', models.DateTimeField(blank=True, help_text='변경일', null=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='삭제일', null=True)),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='제목', max_length=128)),
                ('content', models.CharField(help_text='본문내용', max_length=1000)),
                ('boards', models.ForeignKey(help_text='보드 아이디', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.boards')),
                ('users', models.ForeignKey(help_text='유저 아이디', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.users')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.AddField(
            model_name='boards',
            name='users',
            field=models.ForeignKey(help_text='유저 아이디', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.users'),
        ),
    ]
